import type { AdapterBuilder, AdapterInterface } from '@avedon/shared'
import fs from 'node:fs'
import path from 'node:path'

export type { AdapterBuilder, AdapterInterface }
export type Builder = AdapterBuilder
export type Adapter = AdapterInterface

export type StaticAdapterOptions = {
  out?: string
  /**
   * Write `client/404.html`.
   * - `true` — minimal static not-found shell
   * - `string` — raw HTML body
   */
  notFoundHtml?: boolean | string
  /**
   * When `cloudflare` and `client/_redirects` is missing after `writeClient`,
   * emit a small Cloudflare Pages `_redirects` stub (SPA fallback commented out).
   */
  redirects?: 'cloudflare' | false
}

type ManifestRoute = {
  path?: string
  render?: string
  revalidate?: number
  hasActions?: boolean
  hasApi?: boolean
}

const DEFAULT_404 = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Not found</title>
</head>
<body>
<main>
  <h1>Not found</h1>
  <p>This page does not exist.</p>
  <p><a href="/">Home</a></p>
</main>
</body>
</html>
`

const CF_REDIRECTS_STUB = `# Cloudflare Pages redirects (generated by @avedon/adapter-static)
# Add rules below, or place your own public/_redirects to skip this stub.
# SPA fallback example (uncomment if every unknown path should serve index.html):
# /*    /index.html   200
`

export function ssgHtmlPath(clientDir: string, routePath: string): string {
  const normalized = routePath.split('?')[0] || '/'
  if (normalized.includes('\0')) throw new Error('Invalid SSG path')
  const parts = normalized.split('/').filter(Boolean)
  if (parts.some((p) => p === '..' || p === '.')) {
    throw new Error(`Unsafe SSG path: ${routePath}`)
  }
  if (parts.length === 0) return path.join(clientDir, 'index.html')
  return path.join(clientDir, ...parts, 'index.html')
}

export function assertStaticCompatible(manifest: Record<string, unknown>): void {
  const routes = (manifest.routes ?? []) as ManifestRoute[]
  for (const route of routes) {
    const p = route.path ?? '(unknown)'
    const render = route.render ?? 'ssr'
    if (render !== 'ssg') {
      throw new Error(
        `[@avedon/adapter-static] Route ${p} has render: '${render}' — only render: 'ssg' is allowed.`,
      )
    }
    if (route.hasActions) {
      throw new Error(
        `[@avedon/adapter-static] Route ${p} defines actions — not supported for static export.`,
      )
    }
    if (route.hasApi) {
      throw new Error(
        `[@avedon/adapter-static] Route ${p} defines api handlers — not supported for static export.`,
      )
    }
    if (route.revalidate != null) {
      throw new Error(
        `[@avedon/adapter-static] Route ${p} sets revalidate — ISR requires a server adapter.`,
      )
    }
  }
}

export function staticAdapter(options: StaticAdapterOptions = {}): AdapterInterface {
  const out = options.out ?? 'build'
  return {
    name: '@avedon/adapter-static',
    async adapt(builder) {
      assertStaticCompatible(builder.getManifest())

      const pages = builder.getSsgPages()
      if (pages.length === 0) {
        throw new Error(
          '[@avedon/adapter-static] No SSG pages emitted — ensure every route uses render: \'ssg\' and getStaticPaths where needed.',
        )
      }

      const outDir = path.resolve(out)
      const clientDir = path.join(outDir, 'client')
      builder.mkdirp(outDir)
      builder.mkdirp(clientDir)
      builder.writeClient(clientDir)

      for (const page of pages) {
        const file = ssgHtmlPath(clientDir, page.path)
        builder.mkdirp(path.dirname(file))
        builder.writeFile(file, page.html)
      }

      if (options.notFoundHtml != null && options.notFoundHtml !== false) {
        const html =
          typeof options.notFoundHtml === 'string' ? options.notFoundHtml : DEFAULT_404
        builder.writeFile(path.join(clientDir, '404.html'), html)
      }

      if (options.redirects === 'cloudflare') {
        const redirectsPath = path.join(clientDir, '_redirects')
        if (!fs.existsSync(redirectsPath)) {
          builder.writeFile(redirectsPath, CF_REDIRECTS_STUB)
        }
      }
    },
  }
}

export default staticAdapter
